version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rues
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
    ports:
      - "8000:8000"
